############################################################

############################################################
server:
  #  port: 8003
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
############################################################

############################################################
spring:
  profiles:
    active: dev
  application:
    name: service-user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

############################################################
#
#
#
############################################################
mybatis:
  type-aliases-package: com.hrs.pojo
  mapper-locations: classpath:mapper/*.xml

############################################################
#
# mybatis mapper
#
############################################################
#
mapper:
  mappers: com.hrs.my.mapper.MyMapper
  not-empty: false    #
  identity: MYSQL
#
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
